const PLAN_ID="plan-2";
const plan=[["Assistierte Klimmzüge","32 kg Unterstützung","8–10",3],["Latzug schulterbreit","55 kg","8–12",3],["T-Bar-Rudern","25 kg","8–12",3],["Bankdrücken","20 kg","8–12",3],["Beinpresse","91 kg","10–15",3],["Schulterpresse","34 kg","8–12",3],["Beinheben","Körpergewicht","8–12",3],["Bird Dog","Körpergewicht","8–10 je Seite",2]];
const seed=[["07.10.2026",[["Assistierte Klimmzüge","32 kg",["8","8","8"]],["Latzug schulterbreit","60 kg",["8","8"]],["T-Bar-Rudern","25 kg",["12","12"]],["Bankdrücken","20 kg",["12","12","9"]],["Beinpresse","91 kg",["15","15"]],["Schulterpresse","34 kg",["10","8"]],["Beinheben","Körpergewicht",["12","10"]],["Bird Dog","Körpergewicht",[]]]],["04.10.2026",[["Assistierte Klimmzüge","32 kg",["8","9","9"]],["Latzug schulterbreit","55 kg",["10","11","12"]],["T-Bar-Rudern","25 kg",["12","11","9"]],["Bankdrücken","20 kg",["12","11","9"]],["Beinpresse","91 kg",["15","15","15"]],["Schulterpresse","32 kg",["12","12"]],["Beinheben","Körpergewicht",["11","11","8"]],["Bird Dog","Körpergewicht",[]]]],["30.09.2026",[["Assistierte Klimmzüge","32 kg",["8","9","8"]],["Latzug schulterbreit","55 kg",["10","10","9"]],["T-Bar-Rudern","25 kg",["11","10","9"]],["Bankdrücken","20 kg",["12","11","9"]],["Beinpresse","87 kg",["15","12"]],["Schulterpresse","34 kg",[]],["Beinheben","Körpergewicht",[]],["Bird Dog","Körpergewicht",[]]]]];
const defaults={goal:{id:"goal-1",name:"1 sauberer Klimmzug",status:"active",current:"32 kg Unterstützung",next:"25 kg Unterstützung",roadmap:["32 kg Unterstützung","25 kg Unterstützung","20 kg Unterstützung","15 kg Unterstützung","10 kg Unterstützung","1 sauberer Klimmzug"]},plans:[{id:"plan-1",name:"Plan 1 · Klimmzug-Fokus",from:"01.07.2026",to:"05.09.2026",active:false},{id:"plan-2",name:"Plan 2 · Ganzkörper",from:"06.09.2026",to:null,active:true}]};
function load(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}}
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
let workouts=load("fitness.workouts",seed.map(x=>({date:x[0],planId:PLAN_ID,items:x[1]})));
let goal=load("fitness.goal",defaults.goal),plans=load("fitness.plans",defaults.plans);
function dateVal(s){return new Date(s.split(".").reverse().join("-"))}
function route(){return location.hash.slice(1)||"home"}
function nav(r){location.hash=r}
function render(){const r=route();document.getElementById("app").innerHTML=view(r);document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.toggle("active",b.dataset.route===r))}
function view(r){if(r==="home")return home();if(r==="train")return train();if(r==="history")return historyView();if(r==="progress")return progress();return more()}
function home(){const steps=goal.roadmap.map((x,i)=>`<div class="step ${i===0?"active":""}"><div class="dot">${i===goal.roadmap.length-1?"🏆":i+1}</div><div><b>${x}</b><small>${i===0?"Aktuell":i===1?"Nächster Meilenstein":i===goal.roadmap.length-1?"Ziel":"Meilenstein"}</small></div></div>`).join("");return `<header><h1>🏋️ Fitness</h1><div class="sub">Dein aktueller Stand</div></header><div class="card hero"><div class="eyebrow">AKTIVES ZIEL</div><div class="goal">${goal.name}</div><div class="current"><div><span>Aktueller Stand</span><br><strong>${goal.current}</strong></div><div style="text-align:right"><span>Nächster Meilenstein</span><br><b>${goal.next}</b></div></div><div class="roadmap">${steps}</div></div><div class="section-title">Aktueller Trainingsplan</div>${plan.map((x,i)=>`<div class="card"><div class="plan-row"><div class="num">${i+1}</div><div><div class="exercise">${x[0]}</div><div class="weight">${x[1]}</div></div><div class="target">${x[2]}</div></div></div>`).join("")}<div class="actions"><button class="primary" onclick="nav('train')">▶ Neues Training starten</button></div>`}
function draftDefault(){return{planId:PLAN_ID,current:0,items:plan.map(x=>({weight:x[1],reps:Array(x[3]).fill("")}))}}
function train(){const draft=load("fitness.draft",draftDefault()),i=Math.min(draft.current||0,plan.length-1),x=plan[i],item=draft.items[i],done=draft.items.filter(it=>it.reps.some(Boolean)).length;return `<button class="back" onclick="nav('home')">← Zurück</button><header><h2>Training</h2><div class="sub">${done} von ${plan.length} Übungen begonnen</div></header><div class="card" style="padding:12px"><span class="badge">Übung ${i+1} / ${plan.length}</span><span class="note" style="float:right">💾 automatisch gespeichert</span></div><div class="card"><div class="exercise">${x[0]}</div><div class="meta">Ziel: ${x[2]}</div><label style="display:block;margin-top:14px">Gewicht / Unterstützung<input id="activeWeight" class="input" inputmode="decimal" value="${item.weight}"></label><div class="sets">${Array.from({length:x[3]},(_,s)=>`<label>Satz ${s+1}<input class="input activeRep" data-s="${s}" type="number" inputmode="numeric" min="0" value="${item.reps[s]||""}"></label>`).join("")}</div></div><div class="actions"><button class="primary" onclick="saveExercise(${i})">${i===plan.length-1?"Training abschließen":"Übung speichern →"}</button>${i>0?'<button class="secondary" onclick="previousExercise()">← Vorherige Übung</button>':""}</div>`}
function saveExercise(i){const d=load("fitness.draft",draftDefault());d.items[i].weight=document.getElementById("activeWeight").value.trim();d.items[i].reps=[...document.querySelectorAll(".activeRep")].map(e=>e.value.trim());save("fitness.draft",d);if(i===plan.length-1){finishWorkout();return}d.current=i+1;save("fitness.draft",d);render()}
function previousExercise(){const d=load("fitness.draft",draftDefault());d.current=Math.max(0,(d.current||0)-1);save("fitness.draft",d);render()}
function finishWorkout(){const d=load("fitness.draft",null);if(!d)return;const hasData=d.items.some(x=>x.reps.some(Boolean));if(!hasData){alert("Bitte mindestens einen Satz eintragen.");return}workouts.unshift({date:new Date().toLocaleDateString("de-DE"),planId:PLAN_ID,items:plan.map((x,i)=>[x[0],d.items[i].weight,d.items[i].reps])});save("fitness.workouts",workouts);localStorage.removeItem("fitness.draft");nav("history")}
function historyView(){const list=[...workouts].sort((a,b)=>dateVal(b.date)-dateVal(a.date));return `<button class="back" onclick="nav('home')">← Zurück</button><header><h2>Trainingshistorie</h2><div class="sub">Neueste Einheit zuerst · alte Planversionen bleiben erhalten.</div></header>${list.map(w=>`<div class="card"><div class="exercise-head"><b>${w.date}</b><span class="badge">${w.planId}</span></div><table><tr><th>Übung</th><th>Gewicht</th><th>Wdh.</th></tr>${w.items.map(x=>`<tr><td>${x[0]}</td><td>${x[1]}</td><td>${x[2].filter(Boolean).join(" / ")||"–"}</td></tr>`).join("")}</table></div>`).join("")}`}
function progress(){const ordered=[...workouts].sort((a,b)=>dateVal(a.date)-dateVal(b.date)),latest=ordered.at(-1),total=ordered.reduce((s,w)=>s+w.items.reduce((a,x)=>a+x[2].filter(Boolean).length,0),0);if(!latest)return '<header><h2>Fortschritt</h2></header><div class="card">Noch keine Trainingsdaten.</div>';const cards=plan.map((p,i)=>{const vals=ordered.map(w=>Math.max(0,...(w.items[i]?.[2]||[]).map(Number))).filter(Boolean),best=Math.max(0,...vals),target=parseInt(p[2].split("–")[1])||12,pct=Math.min(100,best/target*100);return `<div class="progress-card"><div class="pc-head"><div><div class="exercise">${p[0]}</div><div class="meta">Ziel ${p[2]}</div></div><div class="pc-best">${best||"–"}<small> Wdh.</small></div></div><div class="progressbar"><div style="width:${pct}%"></div></div><div class="pc-stats"><div><span>Aktuelles Gewicht</span><b>${latest.items[i]?.[1]||p[1]}</b></div><div><span>Bestes Satz-Ergebnis</span><b>${best||"–"} Wdh.</b></div></div></div>`}).join("");return `<header><h2>Fortschritt</h2><div class="sub">Deine Entwicklung über alle Trainings</div></header><div class="statgrid"><div class="stat"><b>${ordered.length}</b><span>Trainings</span></div><div class="stat"><b>${total}</b><span>Sätze erfasst</span></div></div><div class="card hero"><div class="eyebrow">LETZTES TRAINING</div><div class="goal" style="font-size:22px">${latest.date}</div><div class="note">${latest.planId}</div></div><div class="section-title">Entwicklung je Übung</div>${cards}`}
function more(){return `<header><h2>Mehr</h2><div class="sub">Verwaltung und Einstellungen</div></header><div class="card"><div class="eyebrow">AKTIVES ZIEL</div><div class="list-item"><div><b>${goal.name}</b><div class="meta">${goal.current} · nächster Meilenstein ${goal.next}</div></div><span class="badge">AKTIV</span></div></div><div class="card"><div class="eyebrow">TRAININGSPLÄNE</div>${plans.map(p=>`<div class="list-item"><div><b>${p.name}</b><div class="meta">${p.from}${p.to?" – "+p.to:" · heute"}</div></div><span class="badge">${p.active?"AKTIV":"ARCHIV"}</span></div>`).join("")}</div><div class="card info"><b>Historische Planversionen</b><div class="note" style="margin-top:6px">Alte Pläne bleiben erhalten. Trainings behalten ihre damalige Planversion.</div></div>`}
window.addEventListener("hashchange",render);document.querySelectorAll(".bottom-nav button").forEach(b=>b.onclick=()=>nav(b.dataset.route));if(!location.hash)location.hash="home";render();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});